-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 15:34:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SE_Walpark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SE_Walpark` DEFAULT CHARACTER SET utf8 ;
USE `SE_Walpark` ;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Veiculo` (
  -- `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Cor` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Data_Hora_Entrada` INT NOT NULL,
  `Data_Hora_Saida` INT NOT NULL,
  `Porte` INT NOT NULL,
  PRIMARY KEY (`Placa`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Vaga` (
  `idVaga` INT NOT NULL AUTO_INCREMENT,
  `Situacao_Vaga` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVaga`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `Valor` FLOAT NOT NULL,
  `Tipo_Pagamento` VARCHAR(20) NOT NULL,
  `Veiculo_idVeiculo` VARCHAR(45) NOT NULL,
  `Vaga_idVaga` INT NOT NULL,
  `Data_hora` INT NULL,
  PRIMARY KEY (`idPagamento`, `Veiculo_idVeiculo`, `Vaga_idVaga`),
  INDEX `fk_Pagamento_Veiculo1_idx` (`Veiculo_idVeiculo`),
  INDEX `fk_Pagamento_Vaga1_idx` (`Vaga_idVaga`),
  CONSTRAINT `fk_Pagamento_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `SE_Walpark`.`Veiculo` (`Placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Vaga1`
    FOREIGN KEY (`Vaga_idVaga`)
    REFERENCES `SE_Walpark`.`Vaga` (`idVaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `Veiculo_idVeiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTicket`, `Veiculo_idVeiculo`),
  INDEX `fk_Ticket_Veiculo1_idx` (`Veiculo_idVeiculo`),
  CONSTRAINT `fk_Ticket_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `SE_Walpark`.`Veiculo` (`Placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SE_Walpark`.`Relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_Walpark`.`Relatorio` (
  `idRelatorio` INT NOT NULL AUTO_INCREMENT,
  `Pagamento_idPagamento` INT NOT NULL,
  `Pagamento_Veiculo_idVeiculo` VARCHAR(45) NOT NULL,
  `Pagamento_Vaga_idVaga` INT NOT NULL,
  PRIMARY KEY (`idRelatorio`, `Pagamento_idPagamento`, `Pagamento_Veiculo_idVeiculo`, `Pagamento_Vaga_idVaga`),
  INDEX `fk_Relatorio_Pagamento1_idx` (`Pagamento_idPagamento`, `Pagamento_Veiculo_idVeiculo`, `Pagamento_Vaga_idVaga`),
  CONSTRAINT `fk_Relatorio_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`, `Pagamento_Veiculo_idVeiculo`, `Pagamento_Vaga_idVaga`)
    REFERENCES `SE_Walpark`.`Pagamento` (`idPagamento`, `Veiculo_idVeiculo`, `Vaga_idVaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
