CREATE DATABASE IF NOT EXISTS agenda;
USE agenda;

CREATE TABLE Grupo (
  idGrupo INT PRIMARY KEY AUTO_INCREMENT,
  nomeGrupo VARCHAR(20) NOT NULL,
  descricao VARCHAR(255) NULL,
  dtCriacao VARCHAR(10) NOT NULL
);

CREATE TABLE Pessoa (
  idPessoa INT PRIMARY KEY AUTO_INCREMENT,
  nomePessoa VARCHAR(12) NOT NULL,
  sobrenome VARCHAR(30) NULL,
  idade INT UNSIGNED NULL,
  email VARCHAR(25) NULL,
  fk_grupo_idGrupo INT NOT NULL,
  
  CONSTRAINT FK_GrupoPessoa FOREIGN KEY (fk_grupo_idGrupo)
  REFERENCES Grupo (idGrupo)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE Telefone (
  idTelefone INT PRIMARY KEY AUTO_INCREMENT,
  ddd VARCHAR(3) NOT NULL,
  telefone VARCHAR(10) NOT NULL,
  fk_pessoa_idPessoa INT NOT NULL,
  
  CONSTRAINT FK_TelefonePessoa FOREIGN KEY (fk_pessoa_idPessoa)
  REFERENCES Pessoa (idPessoa) 
  ON UPDATE CASCADE
  ON DELETE CASCADE
);